package com.abhishek.ecommerce.user;
import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.http.*; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.web.bind.annotation.*; import io.jsonwebtoken.Jwts; import io.jsonwebtoken.security.Keys; import org.springframework.beans.factory.annotation.Value; import java.nio.charset.StandardCharsets; import java.time.Instant; import java.util.Date;
@RestController @RequestMapping("/api/users") public class AuthController {
 record Register(@NotBlank String name,@Email @NotBlank String email,@Size(min=8) String password){} record Login(@Email @NotBlank String email,@NotBlank String password){} record AuthResponse(String token,String userId,String role){}
 private final UserRepository repo; private final PasswordEncoder encoder; private final javax.crypto.SecretKey key;
 public AuthController(UserRepository r,PasswordEncoder e,@Value("${app.jwt.secret}")String s){repo=r;encoder=e;key=Keys.hmacShaKeyFor(s.getBytes(StandardCharsets.UTF_8));}
 @PostMapping("/register") ResponseEntity<?> register(@Valid @RequestBody Register x){if(repo.findByEmail(x.email()).isPresent())return ResponseEntity.status(HttpStatus.CONFLICT).body("Email already registered"); User u=new User();u.setName(x.name());u.setEmail(x.email());u.setPassword(encoder.encode(x.password()));repo.save(u);return ResponseEntity.status(201).body("User registered");}
 @PostMapping("/login") AuthResponse login(@Valid @RequestBody Login x){User u=repo.findByEmail(x.email()).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Invalid credentials"));if(!encoder.matches(x.password(),u.getPassword()))throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Invalid credentials");String t=Jwts.builder().subject(u.getId().toString()).claim("role",u.getRole().name()).claim("email",u.getEmail()).issuedAt(new Date()).expiration(Date.from(Instant.now().plusSeconds(86400))).signWith(key).compact();return new AuthResponse(t,u.getId().toString(),u.getRole().name());}
 @GetMapping("/me") User me(@RequestHeader("X-User-Id") String id){return repo.findById(java.util.UUID.fromString(id)).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"User not found"));}
}